/**
 * Copyright 2026 The ARCORIS Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * commitlint configuration for `arcoris.dev/pool`.
 *
 * Why this file exists:
 * - malformed commit headers make pull requests, squash merges, and repository
 *   history harder to review;
 * - the repository expects Conventional Commit style for both commits and PR
 *   titles;
 * - a repository-level commit convention keeps release notes, review
 *   expectations, and automation behavior consistent.
 *
 * Important:
 * - commitlint does NOT publish releases;
 * - commitlint does NOT replace branch protection;
 * - commitlint does NOT guarantee that a pull request was reviewed;
 * - commitlint only validates that commit messages follow the expected shape.
 *
 * This repository uses Conventional Commit style with a small set of explicit
 * repository-specific rules:
 *
 * Allowed change types:
 * - feat
 * - fix
 * - refactor
 * - perf
 * - docs
 * - test
 * - build
 * - ci
 * - chore
 * - revert
 *
 * Non-release types still allowed in history:
 * - build
 * - ci
 * - chore
 * - docs
 * - test
 * - refactor
 *
 * Breaking changes:
 * - a breaking change should use the `!` marker in the header and a
 *   `BREAKING CHANGE:` footer note;
 * - the rule below enforces both or neither, which keeps the release intent
 *   explicit and avoids partial breaking markers.
 *
 * Notes on scope:
 * - scope is encouraged but not required;
 * - if present, it should be repository-meaningful and kebab-case;
 * - scope is intentionally NOT locked to a tiny enum yet, because repository
 *   areas may evolve and over-restricting scope early creates more friction
 *   than value.
 *
 * Examples:
 * - feat(pool): add explicit reuse admission helper
 * - fix(lifecycle): preserve denial before reset
 * - perf(bench): reduce chart generation overhead
 * - docs(readme): clarify pointer-like guidance
 * - test(backend): cover syncpool miss path
 * - ci(github): tighten release tag gating
 * - chore(deps): update github/codeql-action to v4
 *
 * Bad examples:
 * - fixed stuff
 * - update files
 * - docs: README
 * - feat: Added New Feature
 * - deps(actions): update workflow action
 *
 * The last example is intentionally disallowed for humans. Release-shaped
 * headers are reserved for repository release automation and should not be
 * authored manually.
 */

module.exports = {
  /**
   * Start from the official conventional baseline.
   */
  extends: ['@commitlint/config-conventional'],

  /**
   * Keep default ignore behavior enabled.
   *
   * This allows common autogenerated messages such as merge commits, version
   * tags, and other VCS-generated shapes to bypass ordinary commit linting when
   * appropriate.
   */
  defaultIgnores: true,

  /**
   * Custom parser options.
   *
   * We explicitly recognize the breaking-change footer keywords used elsewhere
   * in the repository release tooling.
   */
  parserPreset: {
    parserOpts: {
      noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES', 'BREAKING'],
    },
  },

  /**
   * Helpful link shown when commitlint fails.
   */
  helpUrl: 'https://www.conventionalcommits.org/en/v1.0.0/',

  rules: {
    /**
     * Core header structure.
     */
    'type-empty': [2, 'never'],
    'type-case': [2, 'always', 'lower-case'],
    'type-enum': [
      2,
      'always',
      [
        'build',
        'ci',
        'chore',
        'docs',
        'feat',
        'fix',
        'perf',
        'refactor',
        'revert',
        'test',
      ],
    ],

    /**
     * Scope policy.
     *
     * Scope is optional, but if a scope is present we expect it to be stable and
     * readable. Kebab-case keeps commit history visually uniform.
     *
     * We do not require `scope-enum` yet because repository areas are still
     * evolving and an early hard allow-list would cause unnecessary churn.
     */
    'scope-case': [2, 'always', ['kebab-case']],
    'scope-max-length': [2, 'always', 40],

    /**
     * Subject policy.
     *
     * Subject should be:
     * - present
     * - concise
     * - not end with a period
     *
     * We intentionally do NOT force one exact subject case. The official
     * conventional configuration already forbids the most problematic cases
     * (sentence/start/pascal/upper), which is a good compromise for practical
     * commit authoring.
     */
    'subject-empty': [2, 'never'],
    'subject-full-stop': [2, 'never', '.'],
    'subject-max-length': [2, 'always', 80],

    /**
     * Overall header quality.
     *
     * Keep the summary line short enough to remain readable in:
     * - GitHub commit lists
     * - release notes
     * - squash-merge dialogs
     *
     * 100 is a pragmatic upper bound: stricter than "anything goes", but not so
     * strict that meaningful scopes and concise subjects become painful.
     */
    'header-max-length': [2, 'always', 100],
    'header-trim': [2, 'always'],

    /**
     * Body / footer formatting.
     *
     * These rules keep longer explanations readable and conventional-commit
     * compliant when a body or footer is present.
     */
    'body-leading-blank': [2, 'always'],
    'footer-leading-blank': [2, 'always'],
    'body-max-line-length': [2, 'always', 100],
    'footer-max-line-length': [2, 'always', 100],

    /**
     * Breaking-change discipline.
     *
     * Enforce both:
     * - `!` in the header
     * - `BREAKING CHANGE:` footer
     *
     * This avoids ambiguous breaking markers and keeps history explicit.
     */
    'breaking-change-exclamation-mark': [2, 'always'],

    /**
     * Repository-specific policy:
     * do not allow manual human-authored release commits.
     *
     * Release automation may still generate `chore(release): x.y.z [skip ci]`
     * or a similar reserved shape. This rule exists to discourage contributors
     * from using release-shaped commits manually in normal development.
     *
     * commitlint cannot express "disallow only some exact commit headers" as a
     * built-in rule, so we enforce it with a simple plugin below.
     */
    'arcoris-no-manual-release-commit': [2, 'always'],
  },

  plugins: [
    {
      rules: {
        /**
         * Reject manual release-commit headers that imitate semantic-release.
         *
         * We allow release automation to create reserved release-shaped headers
         * when needed, but contributors should not use that shape in ordinary
         * development history.
         */
        'arcoris-no-manual-release-commit': ({header}) => {
          const value = header || '';
          const forbidden = /^chore\(release\):\s+\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\s+\[skip ci\])?$/;

          return [
            !forbidden.test(value),
            'do not author manual release commits; release-shaped headers are reserved for release automation',
          ];
        },
      },
    },
  ],

  /**
   * Optional prompt hints for repositories that later adopt
   * `@commitlint/cz-commitlint`.
   *
   * This does not affect plain commitlint CLI validation, but keeping the prompt
   * metadata here documents the intended commit vocabulary and can be reused by
   * interactive tooling later without changing repository policy.
   */
  prompt: {
    settings: {
      enableMultipleScopes: false,
      useEmoji: false,
      useAI: false,
      useSelector: true,
      allowCustomScopes: true,
      defaultScope: '',
      defaultBody: '',
      defaultIssues: '',
      useExclamationMark: true,
    },
    messages: {
      skip: ':skip',
      max: 'upper limit',
      min: 'lower limit',
      emptyWarning: 'cannot be empty',
      upperLimitWarning: 'too long',
      lowerLimitWarning: 'too short',
    },
    questions: {
      type: {
        description: "Select the type of change that this commit introduces",
        enum: {
          feat: {
            description: 'A user-visible feature',
            title: 'Features',
            emoji: '',
          },
          fix: {
            description: 'A bug fix',
            title: 'Bug Fixes',
            emoji: '',
          },
          perf: {
            description: 'A performance or allocation improvement',
            title: 'Performance',
            emoji: '',
          },
          revert: {
            description: 'A revert of a previous commit',
            title: 'Reverts',
            emoji: '',
          },
          docs: {
            description: 'Documentation only',
            title: 'Documentation',
            emoji: '',
          },
          test: {
            description: 'Tests only',
            title: 'Tests',
            emoji: '',
          },
          refactor: {
            description: 'Refactoring with no intended behavior change',
            title: 'Refactoring',
            emoji: '',
          },
          build: {
            description: 'Build system or packaging changes',
            title: 'Build',
            emoji: '',
          },
          ci: {
            description: 'CI / workflow changes',
            title: 'CI',
            emoji: '',
          },
          chore: {
            description: 'Repository maintenance that is not otherwise classified',
            title: 'Chores',
            emoji: '',
          },
        },
      },
      scope: {
        description: 'Provide a short repository-meaningful scope (optional)',
      },
      subject: {
        description: 'Write a short imperative summary',
      },
      body: {
        description: 'Provide additional context if needed',
      },
      isBreaking: {
        description: 'Are there breaking changes?',
      },
      breaking: {
        description: 'Describe the breaking change',
      },
      isIssueAffected: {
        description: 'Are any issues affected?',
      },
      issues: {
        description: 'Add issue references (for example: #123)',
      },
    },
  },
};
